### ISSUE TITLE
ERROR in resolving fallback for shared module igv

### ISSUE THREAD

**Issue by khourhin** [epi2me-labs/igv-jupyterlab#1]
First, I think this is an awesome initiative and thanks a lot for developping it !

Unfortunately I run into some issues to install the extension. I'm using conda and here is what I have done so far:
```
conda create -n jupyter_test jupyterlab "nodejs>12"
conda activate jupyter_test
pip install igv_jupyterlab
```
So far, so good.
But:
```
jupyter labextension install @jupyter-widgets/jupyterlab-manager @epi2melabs/igv-jupyterlab
```
Returns
> Building jupyterlab assets (production, minimized)
> An error occured.
> RuntimeError: JupyterLab failed to build
> See the log file for details:  /tmp/jupyterlab-debug-7v5ymjtr.log

The log gives apparently this error:

> ERROR in resolving fallback for shared module igv
> Module not found: Error: Can't resolve 'igv' in '/home/khourhin/programs/miniconda3/envs/jupyter_test/share/jupyter/lab/staging/node_modules/@epi2melabs/igv-jupyterlab/lib'
> resolve 'igv' in '/home/khourhin/programs/miniconda3/envs/jupyter_test/share/jupyter/lab/staging/node_modules/@epi2melabs/igv-jupyterlab/lib'

The complete log can be found here:
[jupyterlab-debug-7v5ymjtr.log](https://github.com/epi2me-labs/igv-jupyterlab/files/6050813/jupyterlab-debug-7v5ymjtr.log)

I will keep on investigating but any help is well appreciated !

**Comment by millerh1** [comment]
I have the exact same problem I think... I am running a jupyterhub using a pipenv and then I attempted to build igv-jupyterlab:

```
/opt/jupyterhub/bin/python3 -m jupyter labextension install @jupyter-widgets/jupyterlab-manager @epi2melabs/igv-jupyterlab
```

Which gives:

>Building jupyterlab assets (production, minimized)
An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  /tmp/jupyterlab-debug-vc0p26fl.log

Here is the log ([link](https://misc-items-to-share.s3-us-west-2.amazonaws.com/jupyterlab-debug-vc0p26fl.log))

**Comment by jrobinso** [comment]
This might be an igv.js bug that was fixed recently, there was no "browser" field in package.json.   Most package managers don't need it but some do, including possibly whatever Jupyter is using (webpack?).    Try updating the igv.js import to version 2.7.9.   

This is just an educated guess.

**Comment by khourhin** [comment]
Thanks again for the help @jrobinso !
I just retried the commands from my first post and everything seems to run smootly now (ie no error and apparently a functional igv plugin in jupyter lab). So yes the bug seems to be fixed now. Great !
